# Generated by Django 4.0.3 on 2022-04-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
